use core::ffi::{c_int, c_void};
use core::{mem, ptr};
use crate::early::*;
use crate::terminal::*;
use crate::render::*;
use crate::input::*;
use crate::selection::*;
use crate::kitty_graphics::*;
use crate::mouse_encode::*;
use crate::simple::*;
use crate::event_cell_style::*;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct GhosttySizeReportSize {
    pub(crate) rows: u16,
    pub(crate) columns: u16,
    pub(crate) cell_width: u32,
    pub(crate) cell_height: u32,
}

pub(crate) const SIZE_REPORT_MODE_2048: c_int = 0;
pub(crate) const SIZE_REPORT_CSI_14_T: c_int = 1;
pub(crate) const SIZE_REPORT_CSI_16_T: c_int = 2;
pub(crate) const SIZE_REPORT_CSI_18_T: c_int = 3;
pub(crate) const PASTE_START: &[u8; 6] = b"\x1b[200~";
pub(crate) const PASTE_END: &[u8; 6] = b"\x1b[201~";
pub(crate) const MODE_ANSI_MASK: u16 = 1 << 15;
pub(crate) const MODE_VALUE_MASK: u16 = 0x7fff;
pub(crate) const STYLE_COLOR_NONE: c_int = 0;
pub(crate) const STYLE_COLOR_PALETTE: c_int = 1;
pub(crate) const STYLE_COLOR_RGB: c_int = 2;
pub(crate) const ROW_DATA_WRAP: c_int = 1;
pub(crate) const ROW_DATA_WRAP_CONTINUATION: c_int = 2;
pub(crate) const ROW_DATA_GRAPHEME: c_int = 3;
pub(crate) const ROW_DATA_STYLED: c_int = 4;
pub(crate) const ROW_DATA_HYPERLINK: c_int = 5;
pub(crate) const ROW_DATA_SEMANTIC_PROMPT: c_int = 6;
pub(crate) const ROW_DATA_KITTY_VIRTUAL_PLACEHOLDER: c_int = 7;
pub(crate) const ROW_DATA_DIRTY: c_int = 8;
pub(crate) const CELL_CONTENT_TAG_CODEPOINT: u64 = 0;
pub(crate) const CELL_CONTENT_TAG_CODEPOINT_GRAPHEME: u64 = 1;
pub(crate) const CELL_CONTENT_TAG_BG_COLOR_PALETTE: u64 = 2;
pub(crate) const CELL_CONTENT_TAG_BG_COLOR_RGB: u64 = 3;
pub(crate) const CELL_DATA_CODEPOINT: c_int = 1;
pub(crate) const CELL_DATA_CONTENT_TAG: c_int = 2;
pub(crate) const CELL_DATA_WIDE: c_int = 3;
pub(crate) const CELL_DATA_HAS_TEXT: c_int = 4;
pub(crate) const CELL_DATA_HAS_STYLING: c_int = 5;
pub(crate) const CELL_DATA_STYLE_ID: c_int = 6;
pub(crate) const CELL_DATA_HAS_HYPERLINK: c_int = 7;
pub(crate) const CELL_DATA_PROTECTED: c_int = 8;
pub(crate) const CELL_DATA_SEMANTIC_CONTENT: c_int = 9;
pub(crate) const CELL_DATA_COLOR_PALETTE: c_int = 10;
pub(crate) const CELL_DATA_COLOR_RGB: c_int = 11;
pub(crate) const BUILD_INFO_SIMD: c_int = 1;
pub(crate) const BUILD_INFO_KITTY_GRAPHICS: c_int = 2;
pub(crate) const BUILD_INFO_TMUX_CONTROL_MODE: c_int = 3;
pub(crate) const BUILD_INFO_OPTIMIZE: c_int = 4;
pub(crate) const BUILD_INFO_VERSION_STRING: c_int = 5;
pub(crate) const BUILD_INFO_VERSION_MAJOR: c_int = 6;
pub(crate) const BUILD_INFO_VERSION_MINOR: c_int = 7;
pub(crate) const BUILD_INFO_VERSION_PATCH: c_int = 8;
pub(crate) const BUILD_INFO_VERSION_PRE: c_int = 9;
pub(crate) const BUILD_INFO_VERSION_BUILD: c_int = 10;
pub(crate) const TERMINAL_DATA_COLS: c_int = 1;
pub(crate) const TERMINAL_DATA_ROWS: c_int = 2;
pub(crate) const TERMINAL_DATA_CURSOR_X: c_int = 3;
pub(crate) const TERMINAL_DATA_CURSOR_Y: c_int = 4;
pub(crate) const TERMINAL_DATA_CURSOR_PENDING_WRAP: c_int = 5;
pub(crate) const TERMINAL_DATA_ACTIVE_SCREEN: c_int = 6;
pub(crate) const TERMINAL_DATA_CURSOR_VISIBLE: c_int = 7;
pub(crate) const TERMINAL_DATA_KITTY_KEYBOARD_FLAGS: c_int = 8;
pub(crate) const TERMINAL_DATA_SCROLLBAR: c_int = 9;
pub(crate) const TERMINAL_DATA_CURSOR_STYLE: c_int = 10;
pub(crate) const TERMINAL_DATA_MOUSE_TRACKING: c_int = 11;
pub(crate) const TERMINAL_DATA_TITLE: c_int = 12;
pub(crate) const TERMINAL_DATA_PWD: c_int = 13;
pub(crate) const TERMINAL_DATA_TOTAL_ROWS: c_int = 14;
pub(crate) const TERMINAL_DATA_SCROLLBACK_ROWS: c_int = 15;
pub(crate) const TERMINAL_DATA_WIDTH_PX: c_int = 16;
pub(crate) const TERMINAL_DATA_HEIGHT_PX: c_int = 17;
pub(crate) const TERMINAL_DATA_COLOR_FOREGROUND: c_int = 18;
pub(crate) const TERMINAL_DATA_COLOR_BACKGROUND: c_int = 19;
pub(crate) const TERMINAL_DATA_COLOR_CURSOR: c_int = 20;
pub(crate) const TERMINAL_DATA_COLOR_PALETTE: c_int = 21;
pub(crate) const TERMINAL_DATA_COLOR_FOREGROUND_DEFAULT: c_int = 22;
pub(crate) const TERMINAL_DATA_COLOR_BACKGROUND_DEFAULT: c_int = 23;
pub(crate) const TERMINAL_DATA_COLOR_CURSOR_DEFAULT: c_int = 24;
pub(crate) const TERMINAL_DATA_COLOR_PALETTE_DEFAULT: c_int = 25;
pub(crate) const TERMINAL_DATA_KITTY_IMAGE_STORAGE_LIMIT: c_int = 26;
pub(crate) const TERMINAL_DATA_KITTY_IMAGE_MEDIUM_FILE: c_int = 27;
pub(crate) const TERMINAL_DATA_KITTY_IMAGE_MEDIUM_TEMP_FILE: c_int = 28;
pub(crate) const TERMINAL_DATA_KITTY_IMAGE_MEDIUM_SHARED_MEM: c_int = 29;
pub(crate) const TERMINAL_DATA_KITTY_GRAPHICS: c_int = 30;
pub(crate) const TERMINAL_DATA_SELECTION: c_int = 31;
pub(crate) const RENDER_RESULT_SUCCESS: c_int = GHOSTTY_SUCCESS;
pub(crate) const RENDER_RESULT_INVALID_VALUE: c_int = GHOSTTY_INVALID_VALUE;
pub(crate) const RENDER_DATA_COLS: c_int = 1;
pub(crate) const RENDER_DATA_ROWS: c_int = 2;
pub(crate) const RENDER_DATA_DIRTY: c_int = 3;
pub(crate) const RENDER_DATA_COLOR_BACKGROUND: c_int = 5;
pub(crate) const RENDER_DATA_COLOR_FOREGROUND: c_int = 6;
pub(crate) const RENDER_DATA_COLOR_CURSOR: c_int = 7;
pub(crate) const RENDER_DATA_COLOR_CURSOR_HAS_VALUE: c_int = 8;
pub(crate) const RENDER_DATA_COLOR_PALETTE: c_int = 9;
pub(crate) const RENDER_DATA_CURSOR_VISUAL_STYLE: c_int = 10;
pub(crate) const RENDER_DATA_CURSOR_VISIBLE: c_int = 11;
pub(crate) const RENDER_DATA_CURSOR_BLINKING: c_int = 12;
pub(crate) const RENDER_DATA_CURSOR_PASSWORD_INPUT: c_int = 13;
pub(crate) const RENDER_DATA_CURSOR_VIEWPORT_HAS_VALUE: c_int = 14;
pub(crate) const RENDER_DATA_CURSOR_VIEWPORT_X: c_int = 15;
pub(crate) const RENDER_DATA_CURSOR_VIEWPORT_Y: c_int = 16;
pub(crate) const RENDER_DATA_CURSOR_VIEWPORT_WIDE_TAIL: c_int = 17;
pub(crate) const RENDER_ROW_CELL_DATA_RAW: c_int = 1;
pub(crate) const RENDER_ROW_CELL_DATA_STYLE: c_int = 2;
pub(crate) const RENDER_ROW_CELL_DATA_GRAPHEMES_LEN: c_int = 3;
pub(crate) const RENDER_ROW_CELL_DATA_GRAPHEMES_BUF: c_int = 4;
pub(crate) const RENDER_ROW_CELL_DATA_BG_COLOR: c_int = 5;
pub(crate) const RENDER_ROW_CELL_DATA_FG_COLOR: c_int = 6;
pub(crate) const RENDER_ROW_CELL_DATA_SELECTED: c_int = 7;
pub(crate) const RENDER_ROW_DATA_DIRTY: c_int = 1;
pub(crate) const RENDER_ROW_DATA_RAW: c_int = 2;
pub(crate) const RENDER_ROW_DATA_CELLS: c_int = 3;
pub(crate) const RENDER_ROW_DATA_SELECTION: c_int = 4;
pub(crate) const RENDER_STATE_SET_DIRTY: c_int = 0;
pub(crate) const RENDER_ROW_SET_DIRTY: c_int = 0;
pub(crate) const RENDER_CURSOR_STYLE_BAR: c_int = 0;
pub(crate) const RENDER_CURSOR_STYLE_BLOCK: c_int = 1;
pub(crate) const RENDER_CURSOR_STYLE_UNDERLINE: c_int = 2;
pub(crate) const RENDER_CURSOR_STYLE_BLOCK_HOLLOW: c_int = 3;
pub(crate) const SELECTION_ORDER_FORWARD: c_int = 0;
pub(crate) const SELECTION_ORDER_REVERSE: c_int = 1;
pub(crate) const SELECTION_ORDER_MIRRORED_FORWARD: c_int = 2;
pub(crate) const SELECTION_ORDER_MIRRORED_REVERSE: c_int = 3;
pub(crate) const KEY_EVENT_UTF8_PTR_OFFSET: usize = 0;
pub(crate) const KEY_EVENT_UTF8_LEN_OFFSET: usize = 8;
pub(crate) const KEY_EVENT_ACTION_OFFSET: usize = 16;
pub(crate) const KEY_EVENT_KEY_OFFSET: usize = 20;
pub(crate) const KEY_EVENT_UNSHIFTED_CODEPOINT_OFFSET: usize = 24;
pub(crate) const KEY_EVENT_MODS_OFFSET: usize = 28;
pub(crate) const KEY_EVENT_CONSUMED_MODS_OFFSET: usize = 30;
pub(crate) const KEY_EVENT_COMPOSING_OFFSET: usize = 32;
pub(crate) const MOUSE_EVENT_EVENT_OFFSET: usize = 16;
pub(crate) const MOUSE_EVENT_ACTION_OFFSET: usize = 0;
pub(crate) const MOUSE_EVENT_BUTTON_PAYLOAD_OFFSET: usize = 4;
pub(crate) const MOUSE_EVENT_BUTTON_TAG_OFFSET: usize = 8;
pub(crate) const MOUSE_EVENT_POS_OFFSET: usize = 12;
pub(crate) const MOUSE_EVENT_MODS_OFFSET: usize = 20;
pub(crate) const MOUSE_ACTION_PRESS: c_int = 0;
pub(crate) const MOUSE_ACTION_RELEASE: c_int = 1;
pub(crate) const MOUSE_ACTION_MOTION: c_int = 2;
pub(crate) const MOUSE_BUTTON_LEFT: c_int = 1;
pub(crate) const MOUSE_BUTTON_RIGHT: c_int = 2;
pub(crate) const MOUSE_BUTTON_MIDDLE: c_int = 3;
pub(crate) const MOUSE_BUTTON_FOUR: c_int = 4;
pub(crate) const MOUSE_BUTTON_FIVE: c_int = 5;
pub(crate) const MOUSE_BUTTON_SIX: c_int = 6;
pub(crate) const MOUSE_BUTTON_SEVEN: c_int = 7;
pub(crate) const MOUSE_BUTTON_EIGHT: c_int = 8;
pub(crate) const MOUSE_BUTTON_NINE: c_int = 9;
pub(crate) const MOUSE_TRACKING_NONE: c_int = 0;
pub(crate) const MOUSE_TRACKING_X10: c_int = 1;
pub(crate) const MOUSE_TRACKING_NORMAL: c_int = 2;
pub(crate) const MOUSE_TRACKING_BUTTON: c_int = 3;
pub(crate) const MOUSE_TRACKING_ANY: c_int = 4;
pub(crate) const MOUSE_FORMAT_X10: c_int = 0;
pub(crate) const MOUSE_FORMAT_UTF8: c_int = 1;
pub(crate) const MOUSE_FORMAT_SGR: c_int = 2;
pub(crate) const MOUSE_FORMAT_URXVT: c_int = 3;
pub(crate) const MOUSE_FORMAT_SGR_PIXELS: c_int = 4;
pub(crate) const MOUSE_ENCODER_OPT_ANY_BUTTON_PRESSED: c_int = 3;
pub(crate) const MOUSE_ENCODER_OPT_TRACK_LAST_CELL: c_int = 4;
pub(crate) const KITTY_PLACEMENT_LAYER_ALL: c_int = 0;
pub(crate) const KITTY_PLACEMENT_LAYER_BELOW_BG: c_int = 1;
pub(crate) const KITTY_PLACEMENT_LAYER_BELOW_TEXT: c_int = 2;
pub(crate) const KITTY_PLACEMENT_LAYER_ABOVE_TEXT: c_int = 3;
pub(crate) const KITTY_PLACEMENT_ITERATOR_OPTION_LAYER: c_int = 0;
pub(crate) const KITTY_IMAGE_DATA_ID: c_int = 1;
pub(crate) const KITTY_IMAGE_DATA_NUMBER: c_int = 2;
pub(crate) const KITTY_IMAGE_DATA_WIDTH: c_int = 3;
pub(crate) const KITTY_IMAGE_DATA_HEIGHT: c_int = 4;
pub(crate) const KITTY_IMAGE_DATA_FORMAT: c_int = 5;
pub(crate) const KITTY_IMAGE_DATA_COMPRESSION: c_int = 6;
pub(crate) const KITTY_IMAGE_DATA_PTR: c_int = 7;
pub(crate) const KITTY_IMAGE_DATA_LEN: c_int = 8;
pub(crate) const KITTY_PLACEMENT_DATA_IMAGE_ID: c_int = 1;
pub(crate) const KITTY_PLACEMENT_DATA_PLACEMENT_ID: c_int = 2;
pub(crate) const KITTY_PLACEMENT_DATA_IS_VIRTUAL: c_int = 3;
pub(crate) const KITTY_PLACEMENT_DATA_X_OFFSET: c_int = 4;
pub(crate) const KITTY_PLACEMENT_DATA_Y_OFFSET: c_int = 5;
pub(crate) const KITTY_PLACEMENT_DATA_SOURCE_X: c_int = 6;
pub(crate) const KITTY_PLACEMENT_DATA_SOURCE_Y: c_int = 7;
pub(crate) const KITTY_PLACEMENT_DATA_SOURCE_WIDTH: c_int = 8;
pub(crate) const KITTY_PLACEMENT_DATA_SOURCE_HEIGHT: c_int = 9;
pub(crate) const KITTY_PLACEMENT_DATA_COLUMNS: c_int = 10;
pub(crate) const KITTY_PLACEMENT_DATA_ROWS: c_int = 11;
pub(crate) const KITTY_PLACEMENT_DATA_Z: c_int = 12;
pub(crate) const MOD_SHIFT: u16 = 1 << 0;
pub(crate) const MOD_CTRL: u16 = 1 << 1;
pub(crate) const MOD_ALT: u16 = 1 << 2;
pub(crate) static EMPTY_UTF8: [u8; 0] = [];

