#![no_std]
#![deny(unsafe_op_in_unsafe_fn)]
#![allow(dead_code, unused_imports)]

use core::ffi::{c_int, c_void};
use core::mem;
use core::panic::PanicInfo;
use core::ptr;


mod early;
mod constants;
mod terminal;
mod terminal_lifecycle;
mod terminal_grid_ref;
mod terminal_mode;
mod terminal_point;
mod terminal_resize;
mod terminal_options;
mod terminal_get;
mod terminal_get_color;
mod terminal_get_payload;
mod terminal_get_pointer;
mod terminal_get_selection;
mod terminal_get_scalar;
mod terminal_get_string;
mod terminal_get_style;
mod terminal_set;
mod terminal_set_color;
mod terminal_set_scalar;
mod terminal_set_string;
mod render;
mod render_index;
mod render_row_data;
mod render_row_set;
mod render_cell;
mod render_cell_get;
mod render_cell_style;
mod render_cell_text;
mod render_state;
mod render_state_primitive;
mod render_state_color;
mod input;
mod selection;
mod selection_copy;
mod kitty_geometry;
mod kitty_source;
mod kitty_graphics;
mod kitty_graphics_geom;
mod kitty_image;
mod kitty_rect;
mod kitty_placement_get;
mod kitty_placement_get_one;
mod kitty_placement;
mod kitty_placement_layer;
mod mouse_cell;
mod mouse_button;
mod mouse_button_mods;
mod mouse_encoder_state;
mod mouse_geometry;
mod mouse_encode;
mod mouse_pixels;
mod mouse_report;
mod mouse_types;
mod mouse_setopt;
mod mouse_setopt_bool;
mod mouse_setopt_mode;
mod mouse_setopt_size;
mod mouse_sequence_len;
mod mouse_sequence_write;
mod mouse_viewport;
mod mouse_write;
mod simple;
mod simple_write;
mod size_report;
mod size_report_write;
mod style;
mod style_copy;
mod style_write;
mod event_key;
mod event_key_action;
mod event_key_codepoint;
mod event_key_field;
mod event_key_mods;
mod event_key_utf8;
mod event_mouse;
mod event_mouse_action;
mod event_mouse_button;
mod event_mouse_field;
mod event_mouse_position;
mod paste;
mod paste_bytes;
mod focus;
mod modes;
mod osc;
mod key_options;
mod key_option_as_alt;
mod key_setopt_bool;
mod key_from_terminal;
mod sys;
mod grid_ref;
mod cell;
mod row;
mod terminal_get_kitty_image;
mod sgr_8color;
mod sgr_attr;
mod sgr_basic;
mod sgr_basic_write;
mod sgr_color;
mod sgr_constants;
mod sgr_parse;
mod sgr_state;
mod sgr_underline;
mod sgr_unknown;
mod sgr_write;
mod sgr;
mod color;
mod allocator;
mod build_info;

pub(crate) use early::*;
pub(crate) use constants::*;
pub(crate) use terminal::*;
pub(crate) use terminal_lifecycle::*;
pub(crate) use terminal_grid_ref::*;
pub(crate) use terminal_mode::*;
pub(crate) use terminal_point::*;
pub(crate) use terminal_resize::*;
pub(crate) use terminal_options::*;
pub(crate) use terminal_get::*;
pub(crate) use terminal_get_color::*;
pub(crate) use terminal_get_payload::*;
pub(crate) use terminal_get_pointer::*;
pub(crate) use terminal_get_selection::*;
pub(crate) use terminal_get_scalar::*;
pub(crate) use terminal_get_string::*;
pub(crate) use terminal_get_style::*;
pub(crate) use terminal_set::*;
pub(crate) use terminal_set_color::*;
pub(crate) use terminal_set_scalar::*;
pub(crate) use terminal_set_string::*;
pub(crate) use render::*;
pub(crate) use render_index::*;
pub(crate) use render_row_data::*;
pub(crate) use render_row_set::*;
pub(crate) use render_cell::*;
pub(crate) use render_cell_get::*;
pub(crate) use render_cell_style::*;
pub(crate) use render_cell_text::*;
pub(crate) use render_state::*;
pub(crate) use render_state_primitive::*;
pub(crate) use render_state_color::*;
pub(crate) use input::*;
pub(crate) use selection::*;
pub(crate) use selection_copy::*;
pub(crate) use kitty_geometry::*;
pub(crate) use kitty_source::*;
pub(crate) use kitty_graphics::*;
pub(crate) use kitty_graphics_geom::*;
pub(crate) use kitty_image::*;
pub(crate) use kitty_rect::*;
pub(crate) use kitty_placement_get::*;
pub(crate) use kitty_placement_get_one::*;
pub(crate) use kitty_placement::*;
pub(crate) use kitty_placement_layer::*;
pub(crate) use mouse_cell::*;
pub(crate) use mouse_button::*;
pub(crate) use mouse_button_mods::*;
pub(crate) use mouse_encoder_state::*;
pub(crate) use mouse_geometry::*;
pub(crate) use mouse_encode::*;
pub(crate) use mouse_pixels::*;
pub(crate) use mouse_report::*;
pub(crate) use mouse_types::*;
pub(crate) use mouse_setopt::*;
pub(crate) use mouse_setopt_bool::*;
pub(crate) use mouse_setopt_mode::*;
pub(crate) use mouse_setopt_size::*;
pub(crate) use mouse_sequence_len::*;
pub(crate) use mouse_sequence_write::*;
pub(crate) use mouse_viewport::*;
pub(crate) use mouse_write::*;
pub(crate) use simple::*;
pub(crate) use simple_write::*;
pub(crate) use size_report::*;
pub(crate) use size_report_write::*;
pub(crate) use style::*;
pub(crate) use style_copy::*;
pub(crate) use style_write::*;
pub(crate) use event_key::*;
pub(crate) use event_key_action::*;
pub(crate) use event_key_codepoint::*;
pub(crate) use event_key_field::*;
pub(crate) use event_key_mods::*;
pub(crate) use event_key_utf8::*;
pub(crate) use event_mouse::*;
pub(crate) use event_mouse_action::*;
pub(crate) use event_mouse_button::*;
pub(crate) use event_mouse_field::*;
pub(crate) use event_mouse_position::*;
pub(crate) use paste::*;
pub(crate) use paste_bytes::*;
pub(crate) use focus::*;
pub(crate) use modes::*;
pub(crate) use osc::*;
pub(crate) use key_options::*;
pub(crate) use key_option_as_alt::*;
pub(crate) use key_setopt_bool::*;
pub(crate) use key_from_terminal::*;
pub(crate) use sys::*;
pub(crate) use grid_ref::*;
pub(crate) use cell::*;
pub(crate) use row::*;
pub(crate) use terminal_get_kitty_image::*;
pub(crate) use sgr_8color::*;
pub(crate) use sgr_attr::*;
pub(crate) use sgr_basic::*;
pub(crate) use sgr_basic_write::*;
pub(crate) use sgr_color::*;
pub(crate) use sgr_constants::*;
pub(crate) use sgr_parse::*;
pub(crate) use sgr_state::*;
pub(crate) use sgr_underline::*;
pub(crate) use sgr_unknown::*;
pub(crate) use sgr_write::*;
pub(crate) use sgr::*;
pub(crate) use color::*;
pub(crate) use allocator::*;
pub(crate) use build_info::*;

#[panic_handler]
fn panic(_: &PanicInfo<'_>) -> ! {
    loop {}
}
