#![no_std]
#![deny(unsafe_op_in_unsafe_fn)]
#![allow(dead_code, unused_imports)]

use core::ffi::{c_int, c_void};
use core::mem;
use core::panic::PanicInfo;
use core::ptr;


mod early;
mod constants;
mod ansi;
mod size_types;
mod point;
mod utf8_decoder;
mod vt_parser;
mod charsets;
mod csi;
mod mode_def;
mod device_attributes;
mod device_status;
mod kitty_key;
mod mouse_shape;
mod stream_types;
mod stream_handler;
mod stream_core;
mod stream_csi_dispatch;
mod stream_esc_dispatch;
mod bitmap_allocator;
mod page_types;
mod page_core;
mod page_methods;
mod page_list_types;
mod page_list_methods;
mod reflow_cursor;
mod sgr_attribute;
mod osc_types;
mod osc_encoding;
mod stream_osc_parse;
mod stream_osc_dispatch;
mod stream_terminal;
mod tabstops;
mod hash_map;
mod ref_counted_set;
mod x11_color;
mod tmux;
mod search;
mod selection_codepoints;
mod apc;
mod dcs;
mod screen_set;
mod screen_types;
mod screen_methods;
mod hyperlink;
mod highlight;
mod string_map;
mod terminal;
mod terminal_lifecycle;
mod terminal_grid_ref;
mod terminal_mode;
mod terminal_point;
mod terminal_resize;
mod terminal_options;
mod terminal_types;
mod terminal_methods;
mod terminal_get;
mod terminal_get_color;
mod terminal_get_payload;
mod terminal_get_pointer;
mod terminal_get_selection;
mod terminal_get_scalar;
mod terminal_get_string;
mod terminal_get_style;
mod terminal_set;
mod terminal_set_color;
mod terminal_set_scalar;
mod terminal_set_string;
mod render;
mod render_index;
mod render_row_data;
mod render_row_set;
mod render_cell;
mod render_cell_get;
mod render_cell_style;
mod render_cell_text;
mod render_state;
mod render_state_primitive;
mod render_state_color;
mod input;
mod selection;
mod selection_copy;
mod selection_types;
mod kitty_geometry;
mod kitty_source;
mod kitty_graphics;
mod kitty_graphics_geom;
mod kitty_image;
mod kitty_rect;
mod kitty_placement_get;
mod kitty_placement_get_one;
mod kitty_placement;
mod kitty_placement_layer;
mod kitty_color;
mod kitty_graphics_command;
mod kitty_graphics_exec;
mod kitty_graphics_image;
mod kitty_graphics_storage;
mod kitty_graphics_unicode;
mod mouse_cell;
mod mouse_button;
mod mouse_button_base;
mod mouse_button_required;
mod mouse_button_default;
mod mouse_button_motion;
mod mouse_button_mods;
mod mouse_commit;
mod mouse_encoder_state;
mod mouse_encode_size;
mod mouse_geometry;
mod mouse_encode;
mod mouse_last_cell;
mod mouse_output;
mod mouse_out_written;
mod mouse_pixels;
mod mouse_report;
mod mouse_types;
mod mouse_setopt;
mod mouse_setopt_bool;
mod mouse_setopt_bool_write;
mod mouse_setopt_mode;
mod mouse_setopt_size;
mod mouse_setopt_size_write;
mod mouse_sequence_len;
mod mouse_sequence_write;
mod mouse_size;
mod mouse_suppress;
mod mouse_viewport;
mod mouse_viewport_report;
mod mouse_write;
mod mouse_x10;
mod simple;
mod simple_write;
mod size_report;
mod size_report_encode;
mod size_report_len;
mod size_report_pixels;
mod size_report_write;
mod size_report_write_14;
mod size_report_write_16;
mod size_report_write_18;
mod size_report_write_2048;
mod scrollbar_write;
mod style;
mod style_types;
mod style_attrs_copy;
mod style_color;
mod style_color_copy;
mod style_color_none;
mod style_copy;
mod style_default;
mod style_is_default;
mod style_size_copy;
mod style_value_write;
mod style_write;
mod cursor_style;
mod event_key;
mod event_key_action;
mod event_key_codepoint;
mod event_key_field;
mod event_key_mods;
mod event_key_utf8;
mod event_mouse;
mod event_mouse_action;
mod event_mouse_button;
mod event_mouse_field;
mod event_mouse_position;
mod palette_copy;
mod paste;
mod paste_bytes;
mod paste_encode;
mod paste_is_safe;
mod paste_len;
mod paste_safe;
mod paste_sanitize;
mod paste_write;
mod focus;
mod focus_encode;
mod focus_sequence;
mod focus_write;
mod mode_report_buffer;
mod mode_report_encode;
mod mode_report_len;
mod mode_report_state;
mod mode_report_tag;
mod mode_report_write;
mod mode_report_written;
mod modes;
mod osc;
mod osc_command_data;
mod osc_command_data_write;
mod osc_command_type;
mod key_options;
mod key_bool_option;
mod key_option_as_alt_write;
mod key_option_as_alt_value;
mod key_option_as_alt;
mod key_setopt_bool;
mod key_setopt_bool_write;
mod key_from_terminal_write;
mod key_from_terminal;
mod sys;
mod grid_ref;
mod cell;
mod row;
mod terminal_get_kitty_image;
mod sgr_8color;
mod sgr_attr;
mod sgr_basic;
mod sgr_basic_write;
mod sgr_color;
mod sgr_constants;
mod sgr_parse;
mod sgr_state;
mod sgr_underline;
mod sgr_unknown;
mod sgr_write;
mod sgr;
mod color;
mod color_palette;
mod formatter_types;
mod formatter_terminal;
mod formatter_screen;
mod formatter_page;
mod allocator;
mod build_info;

pub(crate) use early::*;
pub(crate) use constants::*;
pub(crate) use ansi::*;
pub(crate) use size_types::*;
pub(crate) use point::*;
pub(crate) use utf8_decoder::*;
pub(crate) use vt_parser::*;
pub(crate) use charsets::*;
pub(crate) use csi::*;
pub(crate) use mode_def::*;
pub(crate) use device_attributes::*;
pub(crate) use device_status::*;
pub(crate) use kitty_key::*;
pub(crate) use mouse_shape::*;
pub(crate) use stream_types::*;
pub(crate) use stream_handler::*;
pub(crate) use stream_core::*;
pub(crate) use stream_terminal::*;
pub(crate) use sgr_attribute::*;
pub(crate) use osc_types::*;
pub(crate) use osc_encoding::*;
pub(crate) use stream_osc_parse::*;
pub(crate) use stream_osc_dispatch::*;
pub(crate) use bitmap_allocator::*;
pub(crate) use page_types::*;
pub(crate) use page_core::*;
pub(crate) use page_list_types::*;
pub(crate) use tabstops::*;
pub(crate) use hash_map::*;
pub(crate) use ref_counted_set::*;
pub(crate) use x11_color::*;
pub(crate) use tmux::*;
pub(crate) use search::*;
pub(crate) use selection_codepoints::*;
pub(crate) use apc::*;
pub(crate) use dcs::*;
pub(crate) use screen_set::*;
pub(crate) use screen_types::*;
pub(crate) use hyperlink::*;
pub(crate) use highlight::*;
pub(crate) use string_map::*;
pub(crate) use terminal::*;
pub(crate) use terminal_lifecycle::*;
pub(crate) use terminal_grid_ref::*;
pub(crate) use terminal_mode::*;
pub(crate) use terminal_point::*;
pub(crate) use terminal_resize::*;
pub(crate) use terminal_options::*;
pub(crate) use terminal_types::*;
pub(crate) use terminal_get::*;
pub(crate) use terminal_get_color::*;
pub(crate) use terminal_get_payload::*;
pub(crate) use terminal_get_pointer::*;
pub(crate) use terminal_get_selection::*;
pub(crate) use terminal_get_scalar::*;
pub(crate) use terminal_get_string::*;
pub(crate) use terminal_get_style::*;
pub(crate) use terminal_set::*;
pub(crate) use terminal_set_color::*;
pub(crate) use terminal_set_scalar::*;
pub(crate) use terminal_set_string::*;
pub(crate) use render::*;
pub(crate) use render_index::*;
pub(crate) use render_row_data::*;
pub(crate) use render_row_set::*;
pub(crate) use render_cell::*;
pub(crate) use render_cell_get::*;
pub(crate) use render_cell_style::*;
pub(crate) use render_cell_text::*;
pub(crate) use render_state::*;
pub(crate) use render_state_primitive::*;
pub(crate) use render_state_color::*;
pub(crate) use input::*;
pub(crate) use selection::*;
pub(crate) use selection_copy::*;
pub(crate) use selection_types::*;
pub(crate) use kitty_geometry::*;
pub(crate) use kitty_source::*;
pub(crate) use kitty_graphics::*;
pub(crate) use kitty_graphics_geom::*;
pub(crate) use kitty_image::*;
pub(crate) use kitty_rect::*;
pub(crate) use kitty_placement_get::*;
pub(crate) use kitty_placement_get_one::*;
pub(crate) use kitty_placement::*;
pub(crate) use kitty_placement_layer::*;
pub(crate) use kitty_color::*;
pub(crate) use kitty_graphics_command::*;
pub(crate) use kitty_graphics_exec::*;
pub(crate) use kitty_graphics_image::*;
pub(crate) use kitty_graphics_storage::*;
pub(crate) use kitty_graphics_unicode::*;
pub(crate) use mouse_cell::*;
pub(crate) use mouse_button::*;
pub(crate) use mouse_button_base::*;
pub(crate) use mouse_button_default::*;
pub(crate) use mouse_button_motion::*;
pub(crate) use mouse_button_mods::*;
pub(crate) use mouse_encoder_state::*;
pub(crate) use mouse_geometry::*;
pub(crate) use mouse_encode::*;
pub(crate) use mouse_last_cell::*;
pub(crate) use mouse_output::*;
pub(crate) use mouse_out_written::*;
pub(crate) use mouse_pixels::*;
pub(crate) use mouse_report::*;
pub(crate) use mouse_types::*;
pub(crate) use mouse_setopt::*;
pub(crate) use mouse_setopt_bool::*;
pub(crate) use mouse_setopt_mode::*;
pub(crate) use mouse_setopt_size::*;
pub(crate) use mouse_sequence_len::*;
pub(crate) use mouse_sequence_write::*;
pub(crate) use mouse_size::*;
pub(crate) use mouse_viewport::*;
pub(crate) use mouse_viewport_report::*;
pub(crate) use mouse_write::*;
pub(crate) use mouse_x10::*;
pub(crate) use simple::*;
pub(crate) use simple_write::*;
pub(crate) use size_report::*;
pub(crate) use size_report_len::*;
pub(crate) use size_report_pixels::*;
pub(crate) use size_report_write::*;
pub(crate) use size_report_write_14::*;
pub(crate) use size_report_write_16::*;
pub(crate) use size_report_write_18::*;
pub(crate) use size_report_write_2048::*;
pub(crate) use scrollbar_write::*;
pub(crate) use style::*;
pub(crate) use style_types::*;
pub(crate) use style_attrs_copy::*;
pub(crate) use style_color::*;
pub(crate) use style_color_copy::*;
pub(crate) use style_color_none::*;
pub(crate) use style_copy::*;
pub(crate) use style_default::*;
pub(crate) use style_is_default::*;
pub(crate) use style_size_copy::*;
pub(crate) use style_value_write::*;
pub(crate) use style_write::*;
pub(crate) use cursor_style::*;
pub(crate) use event_key::*;
pub(crate) use event_key_action::*;
pub(crate) use event_key_codepoint::*;
pub(crate) use event_key_field::*;
pub(crate) use event_key_mods::*;
pub(crate) use event_key_utf8::*;
pub(crate) use event_mouse::*;
pub(crate) use event_mouse_action::*;
pub(crate) use event_mouse_button::*;
pub(crate) use event_mouse_field::*;
pub(crate) use event_mouse_position::*;
pub(crate) use palette_copy::*;
pub(crate) use paste::*;
pub(crate) use paste_bytes::*;
pub(crate) use paste_len::*;
pub(crate) use paste_safe::*;
pub(crate) use paste_sanitize::*;
pub(crate) use paste_write::*;
pub(crate) use focus::*;
pub(crate) use focus_sequence::*;
pub(crate) use focus_write::*;
pub(crate) use mode_report_len::*;
pub(crate) use mode_report_write::*;
pub(crate) use modes::*;
pub(crate) use osc::*;
pub(crate) use osc_command_data::*;
pub(crate) use osc_command_type::*;
pub(crate) use key_options::*;
pub(crate) use key_option_as_alt::*;
pub(crate) use key_setopt_bool::*;
pub(crate) use key_from_terminal::*;
pub(crate) use sys::*;
pub(crate) use grid_ref::*;
pub(crate) use cell::*;
pub(crate) use row::*;
pub(crate) use terminal_get_kitty_image::*;
pub(crate) use sgr_8color::*;
pub(crate) use sgr_attr::*;
pub(crate) use sgr_basic::*;
pub(crate) use sgr_basic_write::*;
pub(crate) use sgr_color::*;
pub(crate) use sgr_constants::*;
pub(crate) use sgr_parse::*;
pub(crate) use sgr_state::*;
pub(crate) use sgr_underline::*;
pub(crate) use sgr_unknown::*;
pub(crate) use sgr_write::*;
pub(crate) use sgr::*;
pub(crate) use color::*;
pub(crate) use color_palette::*;
pub(crate) use formatter_types::*;
pub(crate) use formatter_terminal::*;
pub(crate) use formatter_screen::*;
pub(crate) use formatter_page::*;
pub(crate) use allocator::*;
pub(crate) use build_info::*;

#[panic_handler]
fn panic(_: &PanicInfo<'_>) -> ! {
    loop {}
}
