use crate::constants::*;
use crate::early::*;

#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum MouseShape {
    #[default]
    Default = 0,
    ContextMenu = 1,
    Help = 2,
    Pointer = 3,
    Progress = 4,
    Wait = 5,
    Cell = 6,
    Crosshair = 7,
    Text = 8,
    VerticalText = 9,
    Alias = 10,
    Copy = 11,
    Move = 12,
    NoDrop = 13,
    NotAllowed = 14,
    Grab = 15,
    Grabbing = 16,
    AllScroll = 17,
    ColResize = 18,
    RowResize = 19,
    NResize = 20,
    EResize = 21,
    SResize = 22,
    WResize = 23,
    NeResize = 24,
    NwResize = 25,
    SeResize = 26,
    SwResize = 27,
    EwResize = 28,
    NsResize = 29,
    NeswResize = 30,
    NwseResize = 31,
    ZoomIn = 32,
    ZoomOut = 33,
}

impl MouseShape {
    pub fn from_u16(v: u16) -> Option<Self> {
        match v {
            0 => Some(MouseShape::Default),
            1 => Some(MouseShape::ContextMenu),
            2 => Some(MouseShape::Help),
            3 => Some(MouseShape::Pointer),
            4 => Some(MouseShape::Progress),
            5 => Some(MouseShape::Wait),
            6 => Some(MouseShape::Cell),
            7 => Some(MouseShape::Crosshair),
            8 => Some(MouseShape::Text),
            9 => Some(MouseShape::VerticalText),
            10 => Some(MouseShape::Alias),
            11 => Some(MouseShape::Copy),
            12 => Some(MouseShape::Move),
            13 => Some(MouseShape::NoDrop),
            14 => Some(MouseShape::NotAllowed),
            15 => Some(MouseShape::Grab),
            16 => Some(MouseShape::Grabbing),
            17 => Some(MouseShape::AllScroll),
            18 => Some(MouseShape::ColResize),
            19 => Some(MouseShape::RowResize),
            20 => Some(MouseShape::NResize),
            21 => Some(MouseShape::EResize),
            22 => Some(MouseShape::SResize),
            23 => Some(MouseShape::WResize),
            24 => Some(MouseShape::NeResize),
            25 => Some(MouseShape::NwResize),
            26 => Some(MouseShape::SeResize),
            27 => Some(MouseShape::SwResize),
            28 => Some(MouseShape::EwResize),
            29 => Some(MouseShape::NsResize),
            30 => Some(MouseShape::NeswResize),
            31 => Some(MouseShape::NwseResize),
            32 => Some(MouseShape::ZoomIn),
            33 => Some(MouseShape::ZoomOut),
            _ => None,
        }
    }

    pub fn from_string(v: &str) -> Option<Self> {
        match v {
            "default" | "left_ptr" => Some(MouseShape::Default),
            "context-menu" => Some(MouseShape::ContextMenu),
            "help" | "question_arrow" => Some(MouseShape::Help),
            "pointer" | "hand" => Some(MouseShape::Pointer),
            "progress" | "left_ptr_watch" => Some(MouseShape::Progress),
            "wait" | "watch" => Some(MouseShape::Wait),
            "cell" => Some(MouseShape::Cell),
            "crosshair" | "cross" => Some(MouseShape::Crosshair),
            "text" | "xterm" => Some(MouseShape::Text),
            "vertical-text" => Some(MouseShape::VerticalText),
            "alias" | "dnd-link" => Some(MouseShape::Alias),
            "copy" | "dnd-copy" => Some(MouseShape::Copy),
            "move" | "dnd-move" => Some(MouseShape::Move),
            "no-drop" | "dnd-no-drop" => Some(MouseShape::NoDrop),
            "not-allowed" | "crossed_circle" => Some(MouseShape::NotAllowed),
            "grab" | "hand1" => Some(MouseShape::Grab),
            "grabbing" => Some(MouseShape::Grabbing),
            "all-scroll" | "fleur" => Some(MouseShape::AllScroll),
            "col-resize" => Some(MouseShape::ColResize),
            "row-resize" => Some(MouseShape::RowResize),
            "n-resize" | "top_side" => Some(MouseShape::NResize),
            "e-resize" | "right_side" => Some(MouseShape::EResize),
            "s-resize" | "bottom_side" => Some(MouseShape::SResize),
            "w-resize" | "left_side" => Some(MouseShape::WResize),
            "ne-resize" | "top_right_corner" => Some(MouseShape::NeResize),
            "nw-resize" | "top_left_corner" => Some(MouseShape::NwResize),
            "se-resize" | "bottom_right_corner" => Some(MouseShape::SeResize),
            "sw-resize" | "bottom_left_corner" => Some(MouseShape::SwResize),
            "ew-resize" => Some(MouseShape::EwResize),
            "ns-resize" => Some(MouseShape::NsResize),
            "nesw-resize" => Some(MouseShape::NeswResize),
            "nwse-resize" => Some(MouseShape::NwseResize),
            "zoom-in" => Some(MouseShape::ZoomIn),
            "zoom-out" => Some(MouseShape::ZoomOut),
            _ => None,
        }
    }
}
