use core::ffi::c_int;

pub(crate) const TERMINAL_OPT_USERDATA: c_int = 0;
pub(crate) const TERMINAL_OPT_WRITE_PTY: c_int = 1;
pub(crate) const TERMINAL_OPT_BELL: c_int = 2;
pub(crate) const TERMINAL_OPT_ENQUIRY: c_int = 3;
pub(crate) const TERMINAL_OPT_XTVERSION: c_int = 4;
pub(crate) const TERMINAL_OPT_TITLE_CHANGED: c_int = 5;
pub(crate) const TERMINAL_OPT_SIZE: c_int = 6;
pub(crate) const TERMINAL_OPT_COLOR_SCHEME: c_int = 7;
pub(crate) const TERMINAL_OPT_DEVICE_ATTRIBUTES: c_int = 8;
pub(crate) const TERMINAL_OPT_TITLE: c_int = 9;
pub(crate) const TERMINAL_OPT_PWD: c_int = 10;
pub(crate) const TERMINAL_OPT_COLOR_FOREGROUND: c_int = 11;
pub(crate) const TERMINAL_OPT_COLOR_BACKGROUND: c_int = 12;
pub(crate) const TERMINAL_OPT_COLOR_CURSOR: c_int = 13;
pub(crate) const TERMINAL_OPT_COLOR_PALETTE: c_int = 14;
pub(crate) const TERMINAL_OPT_KITTY_IMAGE_STORAGE_LIMIT: c_int = 15;
pub(crate) const TERMINAL_OPT_KITTY_IMAGE_MEDIUM_FILE: c_int = 16;
pub(crate) const TERMINAL_OPT_KITTY_IMAGE_MEDIUM_TEMP_FILE: c_int = 17;
pub(crate) const TERMINAL_OPT_KITTY_IMAGE_MEDIUM_SHARED_MEM: c_int = 18;
pub(crate) const TERMINAL_OPT_APC_MAX_BYTES: c_int = 19;
pub(crate) const TERMINAL_OPT_APC_MAX_BYTES_KITTY: c_int = 20;
pub(crate) const TERMINAL_OPT_SELECTION: c_int = 21;
