//! Emit Rust source for the grapheme precompute table used by ghostty-foundation.
const std = @import("std");
const uucode = @import("uucode");

const Precompute = struct {
    const Key = packed struct(u13) {
        state: uucode.grapheme.BreakState,
        gb1: uucode.x.types.GraphemeBreakNoControl,
        gb2: uucode.x.types.GraphemeBreakNoControl,

        fn index(self: Key) usize {
            return @intCast(@as(u13, @bitCast(self)));
        }
    };

    const Value = packed struct(u4) {
        result: bool,
        state: uucode.grapheme.BreakState,
    };

    const data = precompute: {
        var result: [std.math.maxInt(u13) + 1]Value = undefined;

        const max_state_int = blk: {
            var max: usize = 0;
            for (@typeInfo(uucode.grapheme.BreakState).@"enum".fields) |field| {
                if (field.value > max) max = field.value;
            }
            break :blk max;
        };

        @setEvalBranchQuota(10_000);
        const info = @typeInfo(uucode.x.types.GraphemeBreakNoControl).@"enum";
        for (0..max_state_int + 1) |state_int| {
            for (info.fields) |field1| {
                for (info.fields) |field2| {
                    var state: uucode.grapheme.BreakState = @enumFromInt(state_int);

                    const key: Key = .{
                        .gb1 = @field(uucode.x.types.GraphemeBreakNoControl, field1.name),
                        .gb2 = @field(uucode.x.types.GraphemeBreakNoControl, field2.name),
                        .state = state,
                    };
                    const v = uucode.x.grapheme.computeGraphemeBreakNoControl(
                        key.gb1,
                        key.gb2,
                        &state,
                    );
                    result[key.index()] = .{ .result = v, .state = state };
                }
            }
        }

        break :precompute result;
    };
};

pub fn main() !void {
    var stdout: std.fs.File = .stdout();
    var buffer: [8192]u8 = undefined;
    var writer = stdout.writer(&buffer);
    const w = &writer.interface;

    try w.writeAll(
        \\// @generated by src/tools/grapheme_table_gen.zig — do not edit.
        \\pub const GRAPHEME_TABLE: [u8; 8192] = [
        \\
    );

    for (Precompute.data, 0..) |value, i| {
        const encoded: u8 = @intCast(@as(u4, @bitCast(value)));
        if (i % 16 == 0) try w.writeAll("    ");
        try w.print("0x{X:0>2}, ", .{encoded});
        if (i % 16 == 15) try w.writeAll("\n");
    }

    try w.writeAll(
        \\];
        \\
    );
    try w.flush();
}
