const std = @import("std");
const uucode = @import("uucode");
const lut = @import("lut");

const Properties = packed struct {
    width: u2 = 0,
    width_zero_in_grapheme: bool = false,
    grapheme_break: uucode.x.types.GraphemeBreakNoControl = .other,
    emoji_vs_base: bool = false,

    fn eql(a: Properties, b: Properties) bool {
        return a.width == b.width and
            a.width_zero_in_grapheme == b.width_zero_in_grapheme and
            a.grapheme_break == b.grapheme_break and
            a.emoji_vs_base == b.emoji_vs_base;
    }
};

fn propsForCodepoint(cp: u21) Properties {
    if (cp > uucode.config.max_code_point) return .{
        .width = 1,
        .width_zero_in_grapheme = true,
        .grapheme_break = .other,
        .emoji_vs_base = false,
    };

    return .{
        .width = uucode.get(.width, cp),
        .width_zero_in_grapheme = uucode.get(.wcwidth_zero_in_grapheme, cp),
        .grapheme_break = uucode.get(.grapheme_break_no_control, cp),
        .emoji_vs_base = uucode.get(.is_emoji_vs_base, cp),
    };
}

fn graphemeVariant(gb: uucode.x.types.GraphemeBreakNoControl) []const u8 {
    return switch (gb) {
        .other => "Other",
        .prepend => "Prepend",
        .regional_indicator => "RegionalIndicator",
        .spacing_mark => "SpacingMark",
        .l => "L",
        .v => "V",
        .t => "T",
        .lv => "Lv",
        .lvt => "Lvt",
        .zwj => "Zwj",
        .zwnj => "Zwnj",
        .extended_pictographic => "ExtendedPictographic",
        .emoji_modifier_base => "EmojiModifierBase",
        .emoji_modifier => "EmojiModifier",
        .indic_conjunct_break_extend => "IndicConjunctBreakExtend",
        .indic_conjunct_break_linker => "IndicConjunctBreakLinker",
        .indic_conjunct_break_consonant => "IndicConjunctBreakConsonant",
    };
}

pub fn main() !void {
    var arena_state = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena_state.deinit();
    const alloc = arena_state.allocator();

    const gen: lut.Generator(
        Properties,
        struct {
            pub fn get(ctx: @This(), cp: u21) !Properties {
                _ = ctx;
                return propsForCodepoint(cp);
            }

            pub fn eql(ctx: @This(), a: Properties, b: Properties) bool {
                _ = ctx;
                return a.eql(b);
            }
        },
    ) = .{};

    const t = try gen.generate(alloc);
    defer alloc.free(t.stage1);
    defer alloc.free(t.stage2);
    defer alloc.free(t.stage3);

    var stdout: std.fs.File = .stdout();
    var buffer: [8192]u8 = undefined;
    var writer = stdout.writer(&buffer);
    const w = &writer.interface;

    try w.writeAll(
        \\// @generated by src/tools/props_table_rust_gen.zig — do not edit.
        \\use super::grapheme::GraphemeBreak;
        \\
        \\#[derive(Debug, Clone, Copy, PartialEq, Eq)]
        \\pub struct Properties {
        \\    pub width: u8,
        \\    pub width_zero_in_grapheme: bool,
        \\    pub grapheme_break: GraphemeBreak,
        \\    pub emoji_vs_base: bool,
        \\}
        \\
        \\impl Properties {
        \\    pub const OUT_OF_RANGE: Self = Self {
        \\        width: 1,
        \\        width_zero_in_grapheme: true,
        \\        grapheme_break: GraphemeBreak::Other,
        \\        emoji_vs_base: false,
        \\    };
        \\}
        \\
    );

    try w.print("const STAGE1: [u16; {}] = [\n", .{t.stage1.len});
    for (t.stage1, 0..) |entry, i| {
        if (i % 16 == 0) try w.writeAll("    ");
        try w.print("{}, ", .{entry});
        if (i % 16 == 15) try w.writeAll("\n");
    }
    try w.writeAll("];\n\n");

    try w.print("const STAGE2: [u16; {}] = [\n", .{t.stage2.len});
    for (t.stage2, 0..) |entry, i| {
        if (i % 16 == 0) try w.writeAll("    ");
        try w.print("{}, ", .{entry});
        if (i % 16 == 15) try w.writeAll("\n");
    }
    try w.writeAll("];\n\n");

    try w.print("const STAGE3: [Properties; {}] = [\n", .{t.stage3.len});
    for (t.stage3, 0..) |entry, i| {
        if (i % 4 == 0) try w.writeAll("    ");
        try w.print(
            "Properties {{ width: {}, width_zero_in_grapheme: {}, grapheme_break: GraphemeBreak::{s}, emoji_vs_base: {} }}, ",
            .{
                entry.width,
                entry.width_zero_in_grapheme,
                graphemeVariant(entry.grapheme_break),
                entry.emoji_vs_base,
            },
        );
        if (i % 4 == 3) try w.writeAll("\n");
    }
    try w.writeAll("];\n\n");

    try w.writeAll(
        \\pub fn get(cp: u32) -> Properties {
        \\    if cp > 0x10FFFF {
        \\        return Properties::OUT_OF_RANGE;
        \\    }
        \\    let high = (cp >> 8) as usize;
        \\    let low = (cp & 0xFF) as u16;
        \\    STAGE3[STAGE2[(STAGE1[high] + low) as usize] as usize]
        \\}
        \\
    );
    try w.flush();
}
