const std = @import("std");
const uucode = @import("uucode");
const lut = @import("lut");

pub fn main() !void {
    var arena_state = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena_state.deinit();
    const alloc = arena_state.allocator();

    const gen: lut.Generator(
        bool,
        struct {
            pub fn get(ctx: @This(), cp: u21) !bool {
                _ = ctx;
                return if (cp > uucode.config.max_code_point)
                    false
                else
                    uucode.get(.is_symbol, @intCast(cp));
            }

            pub fn eql(ctx: @This(), a: bool, b: bool) bool {
                _ = ctx;
                return a == b;
            }
        },
    ) = .{};

    const t = try gen.generate(alloc);
    defer alloc.free(t.stage1);
    defer alloc.free(t.stage2);
    defer alloc.free(t.stage3);

    var stdout: std.fs.File = .stdout();
    var buffer: [8192]u8 = undefined;
    var writer = stdout.writer(&buffer);
    const w = &writer.interface;

    try w.writeAll(
        \\// @generated by src/tools/symbols_table_rust_gen.zig — do not edit.
        \\
    );

    try w.print("const STAGE1: [u16; {}] = [\n", .{t.stage1.len});
    for (t.stage1, 0..) |entry, i| {
        if (i % 16 == 0) try w.writeAll("    ");
        try w.print("{}, ", .{entry});
        if (i % 16 == 15) try w.writeAll("\n");
    }
    try w.writeAll("];\n\n");

    try w.print("const STAGE2: [u16; {}] = [\n", .{t.stage2.len});
    for (t.stage2, 0..) |entry, i| {
        if (i % 16 == 0) try w.writeAll("    ");
        try w.print("{}, ", .{entry});
        if (i % 16 == 15) try w.writeAll("\n");
    }
    try w.writeAll("];\n\n");

    try w.print("const STAGE3: [bool; {}] = [\n", .{t.stage3.len});
    for (t.stage3, 0..) |entry, i| {
        if (i % 16 == 0) try w.writeAll("    ");
        try w.print("{}, ", .{entry});
        if (i % 16 == 15) try w.writeAll("\n");
    }
    try w.writeAll("];\n\n");

    try w.writeAll(
        \\/// Returns whether `cp` is a symbol-like character (see `src/renderer/cell.zig`).
        \\pub fn get(cp: u32) -> bool {
        \\    if cp > 0x10FFFF {
        \\        return false;
        \\    }
        \\    let high = (cp >> 8) as usize;
        \\    let low = (cp & 0xFF) as u16;
        \\    STAGE3[STAGE2[(STAGE1[high] + low) as usize] as usize]
        \\}
        \\
    );
    try w.flush();
}
